name: Deploy to Azure Arc Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Azure Arc server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_ARC_SERVER_IP }}
          username: ${{ secrets.AZURE_ARC_SERVER_USER }}
          password: ${{ secrets.AZURE_ARC_SERVER_PASSWORD }}
          script: |
            set -e  # Exit on error

            echo "Checking if myapp exists..."
            if [ ! -d "~/myapp/.git" ]; then
              echo "Repository not found. Cloning fresh copy..."
              rm -rf ~/myapp
              git clone https://github.com/joshuaombasa/simple-CI-CD-pipeline-for-an-on-prem-Server-managed-via-Azure-Arc..git ~/myapp
            else
              echo "Repository found. Pulling latest changes..."
              cd ~/myapp
              git pull origin main
            fi

            echo "Checking if myapp.service exists..."
            if ! systemctl list-units --full -all | grep -Fq "myapp.service"; then
              echo "Systemd service not found. Creating service..."
              cat <<EOF | sudo tee /etc/systemd/system/myapp.service
            [Unit]
            Description=Flask App
            After=network.target

            [Service]
            User=$USER
            WorkingDirectory=/home/$USER/myapp
            ExecStart=/usr/bin/python3 /home/$USER/myapp/app.py
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOF
              sudo systemctl daemon-reload
              sudo systemctl enable myapp
            fi

            echo "Restarting myapp service..."
            sudo systemctl restart myapp
            sudo systemctl status myapp --no-pager
